import {
  ArrowDownOutlined,
  DownOutlined,
  HeartOutlined,
  CloudUploadOutlined,
  CaretDownOutlined,
  UserOutlined,
  ExportOutlined,
  ExclamationCircleOutlined,
  PlusOutlined,
  CheckCircleFilled,
  EditOutlined,
  RocketOutlined,
  SettingOutlined,
  DesktopOutlined,
  MailOutlined,
} from "@ant-design/icons";

export default {
  downOutlined: DownOutlined,
  heart: HeartOutlined,
  arrowDown: ArrowDownOutlined,
  upload: CloudUploadOutlined,
  downFilled: CaretDownOutlined,
  user: UserOutlined,
  logout: ExportOutlined,
  exclamation: ExclamationCircleOutlined,
  plus: PlusOutlined,
  checkFilled: CheckCircleFilled,
  edit: EditOutlined,
  rocket: RocketOutlined,
  setting: SettingOutlined,
  desktop: DesktopOutlined,
  email: MailOutlined,
};
