import {
  ArrowDownOutlined,
  ArrowLeftOutlined,
  ArrowRightOutlined,
  CaretDownOutlined,
  CheckCircleFilled,
  CloudUploadOutlined,
  DeleteOutlined,
  DesktopOutlined,
  DoubleRightOutlined,
  DownloadOutlined,
  DownOutlined,
  EditOutlined,
  ExclamationCircleOutlined,
  ExportOutlined,
  HeartFilled,
  HeartOutlined,
  InboxOutlined,
  LoadingOutlined,
  MailOutlined,
  PaperClipOutlined,
  PlusOutlined,
  RocketOutlined,
  SettingOutlined,
  UserOutlined,
} from "@ant-design/icons";

export default {
  arrowDown: ArrowDownOutlined,
  arrowLeft: ArrowLeftOutlined,
  arrowRight: ArrowRightOutlined,
  arrowRightDouble: DoubleRightOutlined,
  downOutlined: DownOutlined,
  heartOutlined: HeartOutlined,
  heartFilled: HeartFilled,
  download: DownloadOutlined,
  upload: CloudUploadOutlined,
  downFilled: CaretDownOutlined,
  user: UserOutlined,
  logout: ExportOutlined,
  exclamation: ExclamationCircleOutlined,
  plus: PlusOutlined,
  checkFilled: CheckCircleFilled,
  edit: EditOutlined,
  rocket: RocketOutlined,
  setting: SettingOutlined,
  desktop: DesktopOutlined,
  email: MailOutlined,
  inbox: InboxOutlined,
  paperClip: PaperClipOutlined,
  delete: DeleteOutlined,
  loading: LoadingOutlined,
};
