import {
  ArrowDownOutlined,
  DownloadOutlined,
  DownOutlined,
  HeartOutlined,
  CloudUploadOutlined,
  CaretDownOutlined,
  UserOutlined,
  ExportOutlined,
  ExclamationCircleOutlined,
  PlusOutlined,
  CheckCircleFilled,
  EditOutlined,
  RocketOutlined,
  SettingOutlined,
  DesktopOutlined,
  MailOutlined,
  InboxOutlined,
  PaperClipOutlined,
  DeleteOutlined,
  ArrowRightOutlined,
} from "@ant-design/icons";

export default {
  downOutlined: DownOutlined,
  heart: HeartOutlined,
  download: DownloadOutlined,
  arrowDown: ArrowDownOutlined,
  arrowRight: ArrowRightOutlined,
  upload: CloudUploadOutlined,
  downFilled: CaretDownOutlined,
  user: UserOutlined,
  logout: ExportOutlined,
  exclamation: ExclamationCircleOutlined,
  plus: PlusOutlined,
  checkFilled: CheckCircleFilled,
  edit: EditOutlined,
  rocket: RocketOutlined,
  setting: SettingOutlined,
  desktop: DesktopOutlined,
  email: MailOutlined,
  inbox: InboxOutlined,
  paperClip: PaperClipOutlined,
  delete: DeleteOutlined,
};
