name: build
on:
  workflow_run:
    workflows: [ci]
    types: ["completed"]
    branches: ["main"]

jobs:
  info:
    name: Collect information
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion != 'failure' && github.event.repository.full_name == 'reearth/reearth-marketplace' && github.event.workflow_run.head_branch == 'main'
    outputs:
      sha_short: ${{ steps.info.outputs.sha_short }}
      new_tag: ${{ steps.info.outputs.new_tag}}
      new_tag_short: ${{ steps.info.outputs.new_tag_short }}
      name: ${{ steps.info.outputs.name }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: fetch tags
        run: git fetch --prune --unshallow --tags
      - name: Get info
        id: info
        run:  |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          TAG=$(git tag --points-at HEAD)
          if [[ ! -z "$TAG" ]]; then
            echo "::set-output name=new_tag::$TAG"
            echo "::set-output name=new_tag_short::${TAG#v}"
          else
            echo "::set-output name=name::nightly"
          fi
      - name: Show info
        env:
          SHA_SHORT: ${{ steps.info.outputs.sha_short }}
          NEW_TAG: ${{ steps.info.outputs.new_tag }}
          NEW_TAG_SHORT: ${{ steps.info.outputs.new_tag_short }}
          NAME: ${{ steps.info.outputs.name }}
        run: echo "sha_short=$SHA_SHORT, new_tag=$NEW_TAG, new_tag_short=$NEW_TAG_SHORT, name=$NAME"

  docker:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    needs:
      - info
    if: needs.info.outputs.name || needs.info.outputs.tag
    env:
      IMAGE_NAME: reearth/reearth-marketplace
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get options
        id: options
        env:
          TAG: ${{ needs.info.outputs.tag_short }}
          NAME: ${{ needs.info.outputs.name }}
          SHA: ${{ needs.info.outputs.sha_short }}
        run: |
          if [[ -n $TAG ]]; then
            PLATFORMS=linux/amd64
            VERSION=$TAG
            TAGS=$IMAGE_NAME:$TAG
            if [[ ! $TAG =~ '-' ]]; then
              TAGS+=,${IMAGE_NAME}:${TAG%.*}
              TAGS+=,${IMAGE_NAME}:${TAG%%.*}
              TAGS+=,${IMAGE_NAME}:latest
            fi
          else
            PLATFORMS=linux/amd64
            VERSION=$SHA
            TAGS=$IMAGE_NAME:$NAME
          fi
          echo "::set-output name=platforms::$PLATFORMS"
          echo "::set-output name=version::$VERSION"
          echo "::set-output name=tags::$TAGS"
      - name: Download web arfiacts
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GPT }}
          workflow: ci.yml
          workflow_conclusion: success
          branch: main
          name: reearth-marketplace-web
          check_artifacts: true
      - name: Extract
        run: tar -xvf reearth-marketplace-web.tar.gz && mv reearth-marketplace-web server/web
      - name: Build and push docker image
        uses: docker/build-push-action@v3
        with:
          context: ./server
          platforms: ${{ steps.options.outputs.platforms }}
          push: true
          build-args: VERSION=${{ steps.options.outputs.version }}
          tags: ${{ steps.options.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=docker,dest=/tmp/$${{ steps.options.tags }}
      - name: setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: Make dir
        run: mkdir reearth
      - name: Save docker image
        run: docker save ${{ steps.options.outputs.tags }} -o ${{ steps.options.outputs.tags }}.tar
      - name: Save imaged to artifact
        uses: actions/upload-artifact@v2
        with:
          name: reearth-marketplace
          path: ${{ steps.options.outputs.tags }}.tar
          if-no-files-found: errors
