name: deploy-web-nightly
on:
  workflow_dispatch:
  workflow_call:
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
env:
  IMAGE_TAG: ${{ vars.DEFAULT_IMAGE_TAG }}  
jobs:
  deploy_test:
    runs-on: ubuntu-latest
    if: github.event.repository.full_name == 'reearth/reearth-marketplace'
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          service_account: ${{ vars.GCP_SA_EMAIL }}
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
          - name: Set up Cloud SDK
          uses: google-github-actions/setup-gcloud@v2
        - name: Configure docker
          run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
        - name: docker push
          run: |
            docker pull ${{ vars.WEB_IMAGE_NAME }}:$IMAGE_TAG
            docker tag ${{ vars.WEB_IMAGE_NAME }}:$IMAGE_TAG ${{ vars.WEB_IMAGE_NAME_GCP }}:IMAGE_TAG
            docker push ${{ vars.WEB_IMAGE_NAME_GCP }}:IMAGE_TAG
        - name: Deploy to Cloud Run
          run: |
            gcloud run deploy ${{ vars.WEB_SERVICE_NAME }} \
              --image ${{ vars.WEB_IMAGE_NAME_GCP }}:IMAGE_TAG \
              --region ${{ vars.GCP_REGION }} \
              --platform managed \
              --quiet
